Copy srpm sources if unable to unpack
Since we are using rpmdev-extract a failure to extract most likely means
we are dealing with non-archive. So instead of unpacking we just copy it
the same way source.py is doing

This fixes following exception:
Traceback (most recent call last):
File "/home/w0rm/work/projects/fedora-review/src/FedoraReview/review_helper.py", line 130, in run
self.__do_report()
File "/home/w0rm/work/projects/fedora-review/src/FedoraReview/review_helper.py", line 81, in __do_report
self.__run_checks(self.bug.spec_file, self.bug.srpm_file)
File "/home/w0rm/work/projects/fedora-review/src/FedoraReview/review_helper.py", line 102, in __run_checks
writedown=not Settings.no_report)
File "/home/w0rm/work/projects/fedora-review/src/FedoraReview/checks_class.py", line 182, in run_checks
test.run()
File "/home/w0rm/work/projects/fedora-review/src/FedoraReview/checks/generic.py", line 348, in run
f.write(diff)
TypeError: expected a character buffer object